// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ใช้ DIRECT_URL สำหรับ migrations (connection pooling ใช้ไม่ได้กับ migrate)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
