const PENDING_SUBSCRIPTION_EXPIRE_HOURS = Number.parseInt(
  process.env.PENDING_SUBSCRIPTION_EXPIRE_HOURS || "24",
  10
);

export const PENDING_SUBSCRIPTION_EXPIRE_MS =
  (Number.isFinite(PENDING_SUBSCRIPTION_EXPIRE_HOURS)
    ? PENDING_SUBSCRIPTION_EXPIRE_HOURS
    : 24) *
  60 *
  60 *
  1000;

